export const car = {
    "Diesel":[
    {
      id: 1,
      model: "FORD Endeavour",
      price: "₹ 36.26 Lakhs",
      description: "Fuel-efficient, high-torque vehicle using compression ignition, ideal for long-distance driving",
      image: "https://5.imimg.com/data5/SELLER/Default/2020/11/SM/VN/IM/84438736/whatsapp-image-2020-11-27-at-2-18-24-am-500x500.jpeg",
    },  
    {
        id: 2,
        model: "Tata Safari",
        price: "₹ 13.2 Lakhs",
        description: "Fuel-efficient, high-torque vehicle using compression ignition, ideal for long-distance driving",
        image: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Tata/Safari/12798/1755865650056/front-left-side-47.jpg",
    },        
    {
      id: 3,
      model: "Mahindra Scorpio N",
      price: "₹ 12.5 Lakhs",
      description: "Fuel-efficient, high-torque vehicle using compression ignition, ideal for long-distance driving",
      image: "https://images.91wheels.com/assets/c_images/gallery/mahindra/scorpio/mahindra-scorpio-6-1766743994.png?w=850&q=40",
    },
    {
      id: 4,
      model: "Toyota Innova Crysta",
      price: "₹ 21.7 Lakhs",
      description: "Fuel-efficient, high-torque vehicle using compression ignition, ideal for long-distance driving",
      image: "https://images.91wheels.com/assets/c_images/gallery/toyota/innova-crysta/toyota-innova-crysta-3-1767849001.png?w=1100&q=40",
    },
    {
      id: 5,
      model: "Maruti Suzuki Ertiga BS6",
      price: "₹ 11.9 Lakhs",
      description: "Fuel-efficient, high-torque vehicle using compression ignition, ideal for long-distance driving",
      image: "https://images.91wheels.com/assets/c_images/gallery/maruti/ertiga/maruti-ertiga-4-1767874534.png",
    },
    {
      id: 6,
      model: "Mahindra Bolero",
      price: "₹ 10.59 Lakhs",
      description: "Fuel-efficient, high-torque vehicle using compression ignition, ideal for long-distance driving",
      image: "https://banner2.cleanpng.com/20180410/ake/avgwa449x.webp",
    },
    {
      id: 7,
      model: "Toyota Fortuner",
      price: "₹ 47.6 Lakhs",
      description: "Fuel-efficient, high-torque vehicle using compression ignition, ideal for long-distance driving",
      image: "https://images.91wheels.com/assets/c_images/gallery/toyota/fortuner-legender/toyota-fortuner-legender-0-1767849483.png?w=850&q=40",
    },
    {  
      id: 8,
      model: "MG Gloster BS6",
      price: "₹ 34.7 Lakhs",
      description: "Fuel-efficient, high-torque vehicle using compression ignition, ideal for long-distance driving",
      image: "https://prod2.singleinterface.com//files/enterprise/additionalfeatureimage/additionalimages/349472/ADDITIONAL-FEATURE-PRODUCT-DETAILS23860-Dealer-Microsite-assets-Gloster-02-30-12-24-03-45-23.png",
    }
    ],
    "Petrol":[
    {
      id: 15,
      model: "Mahindra Scorpio N",
      price: "₹ 12.5 Lakhs",
      description: "Smooth, quiet personal vehicle using spark-ignited, gasoline-powered internal combustion engine",
      image: "https://i.pinimg.com/originals/f2/cf/5e/f2cf5ef4e4b51d29e3420fc32105c3ca.jpg?nii=t",
    },
    {
      id: 16,
      model: "Toyota Innova Hycross",
      price: "₹ 21.7 Lakhs",
      description: "Smooth, quiet personal vehicle using spark-ignited, gasoline-powered internal combustion engine",
      image: "https://akm-img-a-in.tosshub.com/aajtak/images/photo_gallery/202211/toyota888787.jpg",
    },
    {
      id: 17,
      model: "TATA Punch",
      price: "₹ 5.65 Lakhs",
      description: "Smooth, quiet personal vehicle using spark-ignited, gasoline-powered internal combustion engine",
      image: "https://images.91wheels.com/assets/c_images/gallery/tata/punch/tata-punch-0-1769487768.png?w=800&q=40",
    },
    {
      id: 18,
      model: "Toyota Innova Hycross",
      price: "₹ 21.7 Lakhs",
      description: "Smooth, quiet personal vehicle using spark-ignited, gasoline-powered internal combustion engine",
      image: "https://static.india.com/wp-content/uploads/2023/10/Best-Mileage-5-Petrol-Cars-Under-6-Lakh.png?impolicy=Medium_Widthonly&w=400&h=800",
    },   
    {
      id: 19,
      model: "Maruti Suzuki Ertiga BS6",
      price: "₹ 11.9 Lakhs",
      description: "Smooth, quiet personal vehicle using spark-ignited, gasoline-powered internal combustion engine",
      image: "https://i.pinimg.com/736x/3a/52/47/3a5247de5990c5a83459645625f8d6e8.jpg",
    },
    {
      id: 20,
      model: "Mahindra THAR",
      price: "₹ 10.59 Lakhs",
      description: "Smooth, quiet personal vehicle using spark-ignited, gasoline-powered internal combustion engine",
      image: "https://www.pngall.com/wp-content/uploads/19/Thar-Car-Robust-Build-Quality-PNG.png",
    },
    {
      id: 21,
      model: "Toyota Fortuner",
      price: "₹ 47.6 Lakhs",
      description: "Smooth, quiet personal vehicle using spark-ignited, gasoline-powered internal combustion engine",
      image: "https://toppng.com/uploads/preview/toyota-cars-png-file-11664272840aupqps2kgy.png",
    },
    {  
      id: 22,
      model: "Jeep Compass BS6",
      price: "₹ 34.7 Lakhs",
      description: "Smooth, quiet personal vehicle using spark-ignited, gasoline-powered internal combustion engine",
      image: "https://www.kindpng.com/picc/m/177-1777493_jeep-compass-white-2017-india-hd-png-download.png",
    }
    ],
    "EV":[
    {
      id: 25,
      model: "Mahindra XUV E8",
      price: "₹ 12.5 Lakhs",
      description: "Quiet, efficient vehicle powered by battery, plug-in charging, zero emissions",
      image: "https://images.91wheels.com/assets/c_images/gallery/mahindra/xev-9s/mahindra-xev-9s-6-1766745068.png?w=800&q=40",
    },
    {
      id: 26,
      model: "Mahindra BE 6",
      price: "₹ 12.5 Lakhs",
      description: "Quiet, efficient vehicle powered by battery, plug-in charging, zero emissions",
      image: "https://images.91wheels.com/assets/c_images/gallery/mahindra/be-6e/mahindra-be-6e-4-1767931326.png?w=850&q=40",
    },
    {
      id: 27,
      model: "VinFast VF 6",
      price: "₹ 12.5 Lakhs",
      description: "Quiet, efficient vehicle powered by battery, plug-in charging, zero emissions",
      image: "https://imgd.aeplcdn.com/664x374/n/cw/ec/171545/vf-6-exterior-front-view-45.jpeg?isig=0&q=80",
    },    
    {
      id: 28,
      model: "Toyota Z6 EV",
      price: "₹ 21.7 Lakhs",
      description: "Quiet, efficient vehicle powered by battery, plug-in charging, zero emissions",
      image: "https://png.pngtree.com/png-clipart/20250516/original/pngtree-large-electric-family-car-eco-friendly-6-seater-vehicle-png-image_21006196.png",
    },
    {
      id: 29,
      model: "Maruti Suzuki Vitara EV",
      price: "₹ 11.9 Lakhs",
      description: "Quiet, efficient vehicle powered by battery, plug-in charging, zero emissions",
      image: "https://images.91wheels.com/assets/c_images/gallery/maruti/e-vitara/maruti-e-vitara-0-1769588233.png?w=850&q=40",
    },
    {
      id: 30,
      model: "Mahindra XUV E5",
      price: "₹ 10.59 Lakhs",
      description: "Quiet, efficient vehicle powered by battery, plug-in charging, zero emissions",
      image: "https://images.91wheels.com/assets/c_images/gallery/mahindra/xuv-3xo-ev/mahindra-xuv-3xo-ev-0-1768390523.png?w=850&q=40",
    },
    {
      id: 31,
      model: "Toyota VZ4",
      price: "₹ 47.6 Lakhs",
      description: "Quiet, efficient vehicle powered by battery, plug-in charging, zero emissions",
      image: "https://images.91wheels.com/assets/c_images/gallery/toyota/urban-cruiser-ebella/toyota-urban-cruiser-ebella-0-1769588323.png?w=800&q=40",
    },
    {  
      id: 32,
      model: "MG ZS EV",
      price: "₹ 34.7 Lakhs",
      description: "Quiet, efficient vehicle powered by battery, plug-in charging, zero emissions",
      image: "https://images.91wheels.com/assets/c_images/gallery/mg/windsor-ev/mg-windsor-ev-4-1767846845.png?w=1100&q=40",
    }     
    ],
    "Premium Car":[
    {
      id: 41,
      model: "Range Rover SV",
      price: "₹ 4.66 Crores",
      description: "Superior comfort, advanced technology, refined performance, exquisite materials, and prestige engineering",
      image: "https://autonews-mag.com/autocopy/wp-content/uploads/2021/10/range_rover_fan_club_249512228_391966739275474_2604103449226980382_nz45.jpg",
    },
    {
      id: 42,
      model: "Rolls Royce Phantom",
      price: "₹ 10.48 Crores",
      description: "Superior comfort, advanced technology, refined performance, exquisite materials, and prestige engineering",
      image: "https://www.evoindia.com/evoindia/2022-05/bfe5894f-d29b-48cb-9165-a932ffc91c97/P90462877_highRes_rolls_royce_phantom_.jpg",
    },
    {
      id: 43,
      model: "Land Rover Defender",
      price: "₹ 2.66 Crores",
      description: "Superior comfort, advanced technology, refined performance, exquisite materials, and prestige engineering",
      image: "https://motoringworld.in/wp-content/uploads/2022/05/NEW-LAND-ROVER-DEFENDER-130.jpg",
    },    
    {
      id: 44,
      model: "Toyota Land Cruiser",
      price: "₹ 2.78 Crores",
      description: "Superior comfort, advanced technology, refined performance, exquisite materials, and prestige engineering",
      image: "https://www.team-bhp.com/forum/attachments/official-new-car-reviews/2863025d1773337362-toyota-land-cruiser-lc300-review-img_6235.jpg",
    },
    {
      id: 45,
      model: "Mercedes Maybach",
      price: "₹ 3.49 Crores",
      description: "Superior comfort, advanced technology, refined performance, exquisite materials, and prestige engineering",
      image: "https://upload.wikimedia.org/wikipedia/commons/b/be/Mercedes-Maybach_S_580_Z223_black_%284%29.jpg",
    },
    {
      id: 46,
      model: "BMW i8",
      price: "₹ 2.37 Crores",
      description: "Superior comfort, advanced technology, refined performance, exquisite materials, and prestige engineering",
      image: "https://cimg2.ibsrv.net/ibimg/hgm/1600x900-1/100/439/2015-bmw-i8_100439334.jpg",
    },
    {
      id: 47,
      model: "Ferrari 488",
      price: "₹ 4.40 Crores",
      description: "Superior comfort, advanced technology, refined performance, exquisite materials, and prestige engineering",
      image: "https://upload.wikimedia.org/wikipedia/commons/0/0d/2018_Ferrari_488_GTB_4.jpg",
    },
    {  
      id: 48,
      model: "Lamborghini Revuelto",
      price: "₹ 8.99 Crores",
      description: "Superior comfort, advanced technology, refined performance, exquisite materials, and prestige engineering",
      image: "https://classiccarbuyer.co.uk/hs-fs/hubfs/shutterstock_2509788631.jpg?width=1000&height=666&name=shutterstock_2509788631.jpg",
    }     
    ]
}